window._EXTERNAL_DATA = [
    '2 horses-min.jpg',
    'arabic mosque building in white-min.jpg',
    'glasses_of_soda_with_ice_cubes-wallpaper-960x540-min.jpg',
    'nature_mighty_bald eagle-min.jpg',
    'photo (1)-min.jpg',
    'photo (10)-min.jpg',
    'photo (11)-min.jpg',
    'photo (12)-min.jpg',
    'photo (13)-min.jpg',
    'photo (2)-min.jpg',
    'photo (3)-min.jpg',
    'photo (4)-min.jpg',
    'photo (5)-min.jpg',
    'photo (6)-min.jpg',
    'photo (7)-min.jpg',
    'photo (8)-min.jpg',
    'photo (9)-min.jpg',
    'see_funny_lazy_cat-wallpaper-960x600-min.jpg',
    'two_black_headed_gulls-min.jpg',
    'what_a_cute_owl-wallpaper-960x600-min.jpg',
];