function writeHeader() { writeHeader(false); }
function writeHeader(virtuozo) {
  document.write('<a class="company-logo" href="http://www.parallels.com">Parallels</a><div class="header-area"><h1><a class="product-logo" href="http://www.parallels.com/plesk/" title="Parallels Plesk Panel">Parallels Plesk Panel</a></h1><span class="header-text"><a class="top-copyright" href="http://www.parallels.com">&copy; 1999-2009, Parallels<br />All rights reserved</a>');
  if (virtuozo) { document.write('<a class="txt-banner" href="http://www.parallels.com/virtuozzo/">Discover <strong>Parallels<br />Virtuozzo Containers</strong></a>'); }
  document.write('</span></div>');
}
function writeFooter() { writeFooter(true); }
function writeFooter(virtuozzo) {
  document.write('<p class="description">This page was generated by <a href="http://www.parallels.com/en/products/plesk/">Parallels Plesk Panel</a></p>');
  if (virtuozzo) { }
}
function writeCopyFlag() {
  document.write('<script language="javascript" type="text/javascript" src="http://' + location.hostname + ':8880/javascript/promo-flags.js.php"></' + 'script>\n');
}
