window._EXTERNAL_DATA = [
    {
        id: 1,
        name: '2 horses-min.jpg',
        imageUrl: './external-data/pictures/2 horses-min.jpg',
        url: './unique-url-2 horses-min.jpg',
        description: `Desc 2 horses-min.jpg`,
        width: 3,
        height: 2,
    },
    {
        id: 2,
        name: 'arabic mosque building in white-min.jpg',
        imageUrl: './external-data/pictures/arabic mosque building in white-min.jpg',
        url: './unique-url-arabic mosque building in',
        description: `Desc arabic mosque building in white-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 3,
        name: 'glasses_of_soda_with_ice_cubes-wallpaper-960x540-min.jpg',
        imageUrl: './external-data/pictures/glasses_of_soda_with_ice_cubes-wallpaper-960x540-min.jpg',
        url: './unique-url-glasses_of_soda_with_ice_cubes-wallpaper-960x540-min',
        description: `Desc glasses_of_soda_with_ice_cubes-wallpaper-960x540-min.jpg`,
        width: 9,
        height: 6,
    },
    {
        id: 4,
        name: 'nature_mighty_bald eagle-min.jpg',
        imageUrl: './external-data/pictures/nature_mighty_bald eagle-min.jpg',
        url: './unique-url-nature_mighty_bald eagle-min.jpg',
        description: `Desc nature_mighty_bald eagle-min.jpg`,
        width: 12,
        height: 8,
    },
    {
        id: 5,
        name: 'photo (1)-min.jpg',
        imageUrl: './external-data/pictures/photo (1)-min.jpg',
        url: './unique-url-photo (1)-min',
        description: `Desc photo (1)-min.jpg`,
        width: 15,
        height: 10,
    },
    {
        id: 6,
        name: 'photo (10)-min.jpg',
        imageUrl: './external-data/pictures/photo (10)-min.jpg',
        url: './unique-url-photo (10)-min',
        description: `Desc photo (10)-min.jpg`,
        width: 18,
        height: 12,
    },
    {
        id: 7,
        name: 'photo (11)-min.jpg',
        imageUrl: './external-data/pictures/photo (11)-min.jpg',
        url: './unique-url-photo (11)-min',
        description: `Desc photo (11)-min.jpg`,
        width: 21,
        height: 14,
    },
    {
        id: 8,
        name: 'photo (12)-min.jpg',
        imageUrl: './external-data/pictures/photo (12)-min.jpg',
        url: './unique-url-photo (12)-min',
        description: `Desc photo (12)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 9,
        name: 'photo (13)-min.jpg',
        imageUrl: './external-data/pictures/photo (13)-min.jpg',
        url: './unique-url-photo (13)-min',
        description: `Desc photo (13)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 10,
        name: 'photo (2)-min.jpg',
        imageUrl: './external-data/pictures/photo (2)-min.jpg',
        url: './unique-url-photo (2)-min',
        description: `Desc photo (2)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 11,
        name: 'photo (3)-min.jpg',
        imageUrl: './external-data/pictures/photo (3)-min.jpg',
        url: './unique-url-photo (3)-min',
        description: `Desc photo (3)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 12,
        name: 'photo (4)-min.jpg',
        imageUrl: './external-data/pictures/photo (4)-min.jpg',
        url: './unique-url-photo (4)-min',
        description: `Desc photo (4)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 13,
        name: 'photo (5)-min.jpg',
        imageUrl: './external-data/pictures/photo (5)-min.jpg',
        url: './unique-url-photo (5)-min',
        description: `Desc photo (5)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 14,
        name: 'photo (6)-min.jpg',
        imageUrl: './external-data/pictures/photo (6)-min.jpg',
        url: './unique-url-photo (6)-min',
        description: `Desc photo (6)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 15,
        name: 'photo (7)-min.jpg',
        imageUrl: './external-data/pictures/photo (7)-min.jpg',
        url: './unique-url-photo (7)-min',
        description: `Desc photo (7)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 16,
        name: 'photo (8)-min.jpg',
        imageUrl: './external-data/pictures/photo (8)-min.jpg',
        url: './unique-url-photo (8)-min',
        description: `Desc photo (8)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 17,
        name: 'photo (9)-min.jpg',
        imageUrl: './external-data/pictures/photo (9)-min.jpg',
        url: './unique-url-photo (9)-min',
        description: `Desc photo (9)-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 18,
        name: 'see_funny_lazy_cat-wallpaper-960x600-min.jpg',
        imageUrl: './external-data/pictures/see_funny_lazy_cat-wallpaper-960x600-min.jpg',
        url: './unique-url-see_funny_lazy_cat-wallpaper-960x600-min',
        description: `Desc see_funny_lazy_cat-wallpaper-960x600-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 19,
        name: 'two_black_headed_gulls-min.jpg',
        imageUrl: './external-data/pictures/two_black_headed_gulls-min.jpg',
        url: './unique-url-two_black_headed_gulls-min.jpg',
        description: `Desc two_black_headed_gulls-min.jpg`,
        width: 6,
        height: 4,
    },
    {
        id: 20,
        name: 'what_a_cute_owl-wallpaper-960x600-min.jpg',
        imageUrl: './external-data/pictures/what_a_cute_owl-wallpaper-960x600-min.jpg',
        url: './unique-url-what_a_cute_owl-wallpaper-960x600-min',
        description: `Desc what_a_cute_owl-wallpaper-960x600-min.jpg`,
        width: 6,
        height: 4,
    },

];

